### PR TITLE
docs(README.md): install

### PR DESCRIPTION
**Pull request by a8m**
update installation, published in npm and added `@aws` as an owner

### CODE REVIEW

**Comment by ngzhongcai** [comment]
+1

**Comment by shimont** [comment]
+1

**Comment by calexbu** [comment]
We are all still waiting this improvement

**Comment by paparga** [comment]
+1

**Comment by raymolin** [comment]
Thanks for support!  I will gladly add this as a part of the README.  Can you also add aws-dynamodb as one of the owners?

**Comment by a8m** [comment]
Added.
Thx

**Pull request merged**
